

[build]
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production]
  environment = { WORDPRESS_API_URL = "http://tolbertscms.com/graphql", }
  
  [functions]
  node_bundler = "esbuild"