

[build]
command   = "npm run build"
publish = ".next"
functions = "out_functions"


[context.production.environment]
WORDPRESS_API_URL = "http://tolbertscms.com/graphql"
HOSTNAME_URL = "https://tolbertsmusic.com"

[[plugins]]
package = "@netlify/plugin-nextjs"

