

[build]
publish = ".next"

[context.production.environment]
NEXT_PUBLIC_WORDPRESS_API_URL = "http://tolbertscms.com/graphql"
NEXT_PUBLIC_HOSTNAME_URL = "https://tolbertsmusic.com"

[[plugins]]
package = "@netlify/plugin-nextjs"

